import { Guide } from '../types'

// Scans src/guides folder for all files
const modules = import.meta.glob('/src/guides/**/*.*', { eager: true, as: 'url' })

export const autoGeneratedGuides: Guide[] = Object.keys(modules).map((path) => {
  const parts = path.split('/')
  
  // Example Path: /src/guides/26/Biology/H/Cell_Structure.pdf
  // parts[3] = "26", parts[4] = "Biology", parts[5] = "H", parts[6] = "Cell_Structure.pdf"
  
  const rawFileName = parts[parts.length - 1]
  const fileNameNoExt = rawFileName.split('.')[0].replace(/_/g, ' ')

  return {
    year: parts[3],
    subject: parts[4],
    level: parts[5],
    name: fileNameNoExt,
    url: modules[path]
  }
})